// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbF4gyPu1ownM_1wAwuKwUQZfUp9t23cc',
    appId: '1:924871265359:web:ad072dd7b2ea2d14e2ae3a',
    messagingSenderId: '924871265359',
    projectId: 'pharma-d27ac',
    authDomain: 'pharma-d27ac.firebaseapp.com',
    storageBucket: 'pharma-d27ac.firebasestorage.app',
    measurementId: 'G-55K638YQS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXuKthNAleNpyiIGEoOKyAKje9_2q1dS4',
    appId: '1:924871265359:android:7f77084253efb16ee2ae3a',
    messagingSenderId: '924871265359',
    projectId: 'pharma-d27ac',
    storageBucket: 'pharma-d27ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgInC06BVTHHJ34tT0W1aCL6rA3XU2m-M',
    appId: '1:924871265359:ios:41f9857f5801429de2ae3a',
    messagingSenderId: '924871265359',
    projectId: 'pharma-d27ac',
    storageBucket: 'pharma-d27ac.firebasestorage.app',
    iosBundleId: 'com.communitypharmacyconnect.pharma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgInC06BVTHHJ34tT0W1aCL6rA3XU2m-M',
    appId: '1:924871265359:ios:21b1ae1ed871a91be2ae3a',
    messagingSenderId: '924871265359',
    projectId: 'pharma-d27ac',
    storageBucket: 'pharma-d27ac.firebasestorage.app',
    iosBundleId: 'com.communitypharmacyconnect.pharma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbF4gyPu1ownM_1wAwuKwUQZfUp9t23cc',
    appId: '1:924871265359:web:9074b1bef6a24a8ee2ae3a',
    messagingSenderId: '924871265359',
    projectId: 'pharma-d27ac',
    authDomain: 'pharma-d27ac.firebaseapp.com',
    storageBucket: 'pharma-d27ac.firebasestorage.app',
    measurementId: 'G-4RZNQ14KCM',
  );
}
